[book]
title = "Anotações de Stallone"
authors = ["Stallone L.S."]
description = "Anotações das atividades e casos excepcionais lidados por Stallone"
src = "src"
language = "pt-br"
text-direction = "ltr"

[output.html]
default-theme = "Rust"
print = { enable = true }

[output.html.search]
limit-results = 30
