[book]
authors = ["Stallone L.S."]
language = "pt-br"
multilingual = false
src = "src"
title = "Administrativo"

[output.html]
destination = "book" 
search = true 
additional-css = ["custom.css"]

[build]
create-missing-sections = true
